version: "3.8"

services:

  portfolio-noelia:
    container_name: portfolio-noelia
    hostname: portfolio-noelia
    image: docker.io/brianwolf94/portfolio-noelia:latest
    restart: always
    expose:
      - 80
    networks:
      - docker-net

networks:
  docker-net:
    name: docker-net
    external: true